# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7b013ed6b2ee2c6af1459e6d3843633fe99506b3b25b520232508b0211a045b30f08b5a63acfd9d2f4ec71de20a7c5b5c4f5779181a37f57cde4a33b09ef17f

test:
  secret_key_base: 13e8a34b110911eb883daf95b73f7761ea68619378f87f7c1906d1c79dbed50639511970fc1ee7c226ef26034efa635639aad317ca3776a5ef76bd11dba0df35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: tv2roRygXjCfqrjQrPNVjLGeDAMuuoEBpDAwq8BLVtzYTuztjJ